title: "Miraj Website"
description: "A personal website powered by GitHub Pages"
baseurl: "" # Leave empty if the site is at username.github.io
url: "https://mirajcs.github.io"

theme: jekyll-theme-minimal  # You can change this to another theme

# Enable plugins for better SEO and feeds
plugins:
  - jekyll-feed
  - jekyll-seo-tag
